version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run:
          name: Validate Dependencies
          command: yarn install --immutable --immutable-cache
      - run:
          name: Run Tests and Coverage
          command: yarn test:ci
      - run:
          name: Run Linter
          command: yarn lint

workflows:
  version: 2
  test:
    jobs:
      - test
